In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes = True)
%matplotlib inline

In [4]:
data1 = pd.read_csv("drive//MyDrive//Google Data Analytics Capstone//Data//Divvy_Trips_2018_Q1.csv")

In [5]:
data1.head()

,01 - Rental Details Rental ID,01 - Rental Details Local Start Time,01 - Rental Details Local End Time,01 - Rental Details Bike ID,01 - Rental Details Duration In Seconds Uncapped,03 - Rental Start Station ID,03 - Rental Start Station Name,02 - Rental End Station ID,02 - Rental End Station Name,User Type,Member Gender,05 - Member Details Member Birthday Year
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

In [6]:
data1.columns

Index(['01 - Rental Details Rental ID', '01 - Rental Details Local Start Time',
       '01 - Rental Details Local End Time', '01 - Rental Details Bike ID',
       '01 - Rental Details Duration In Seconds Uncapped',
       '03 - Rental Start Station ID', '03 - Rental Start Station Name',
       '02 - Rental End Station ID', '02 - Rental End Station Name',
       'User Type', 'Member Gender',
       '05 - Member Details Member Birthday Year'],
      dtype='object')

In [7]:
data1.shape

(387145, 12)

In [8]:
data2 = pd.read_csv("drive//MyDrive//Google Data Analytics Capstone//Data//Divvy_Trips_2018_Q2.csv")

In [9]:
data2.shape

(1048575, 12)

In [10]:
data3 = pd.read_csv("drive//MyDrive//Google Data Analytics Capstone//Data//Divvy_Trips_2018_Q3.csv")

In [11]:
data3.shape

(1513570, 12)

In [12]:
data4 = pd.read_csv("drive//MyDrive//Google Data Analytics Capstone//Data//Divvy_Trips_2018_Q4.csv")

In [13]:
data4.shape

(642686, 12)

**Reading Data From all 4 Files**

In [14]:
data1.head()

,01 - Rental Details Rental ID,01 - Rental Details Local Start Time,01 - Rental Details Local End Time,01 - Rental Details Bike ID,01 - Rental Details Duration In Seconds Uncapped,03 - Rental Start Station ID,03 - Rental Start Station Name,02 - Rental End Station ID,02 - Rental End Station Name,User Type,Member Gender,05 - Member Details Member Birthday Year
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

In [15]:
data2.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,18000527,01-04-2018 00:04,01-04-2018 00:13,3819,499,22,May St & Taylor St,171,May St & Cullerton St,Subscriber,Male,1994.0
1,18000528,01-04-2018 00:06,01-04-2018 00:27,5000,"1,225.00",157,Lake Shore Dr & Wellington Ave,190,Southport Ave & Wrightwood Ave,Subscriber,Male,1965.0
2,18000529,01-04-2018 00:07,01-04-2018 00:23,5165,960,106,State St & Pearson St,106,State St & Pearson St,Customer,NaN,NaN
3,18000530,01-04-2018 00:07,01-04-2018 00:14,3851,434,241,Morgan St & Polk St,171,May St & Cullerton St,Subscriber,Male,1998.0
4,18000531,01-04-2018 00:10,01-04-2018 00:22,5065,709,228,Damen Ave & Melrose Ave,219,Damen Ave & Cortland St,Subscriber,Male,1983.0

In [16]:
data3.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,19244622,2018-07-01 00:00:03,2018-07-01 23:56:11,5429,"86,168.0",140,Dearborn Pkwy & Delaware Pl,106,State St & Pearson St,Customer,NaN,NaN
1,19244623,2018-07-01 00:00:13,2018-07-01 00:06:39,93,386.0,153,Southport Ave & Wellington Ave,250,Ashland Ave & Wellington Ave,Subscriber,Male,1986.0
2,19244624,2018-07-01 00:00:15,2018-07-01 00:23:26,2461,"1,391.0",76,Lake Shore Dr & Monroe St,301,Clark St & Schiller St,Subscriber,Female,1987.0
3,19244625,2018-07-01 00:00:25,2018-07-01 00:23:31,2991,"1,386.0",76,Lake Shore Dr & Monroe St,301,Clark St & Schiller St,Subscriber,Male,1986.0
4,19244626,2018-07-01 00:00:27,2018-07-01 00:11:23,2851,656.0,60,Dayton St & North Ave,166,Ashland Ave & Wrightwood Ave,Subscriber,Male,1961.0

In [17]:
data4.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,20983530,2018-10-01 00:01:17,2018-10-01 00:29:35,4551,"1,698.0",85,Michigan Ave & Oak St,166,Ashland Ave & Wrightwood Ave,Subscriber,Male,1992.0
1,20983531,2018-10-01 00:03:59,2018-10-01 00:10:55,847,416.0,13,Wilton Ave & Diversey Pkwy,144,Larrabee St & Webster Ave,Subscriber,Female,1982.0
2,20983532,2018-10-01 00:05:14,2018-10-01 00:14:08,6188,534.0,59,Wabash Ave & Roosevelt Rd,197,Michigan Ave & Madison St,Subscriber,Male,1986.0
3,20983533,2018-10-01 00:05:48,2018-10-01 00:18:46,6372,778.0,328,Ellis Ave & 58th St,419,Lake Park Ave & 53rd St,Subscriber,Female,1960.0
4,20983534,2018-10-01 00:07:29,2018-10-01 00:25:51,1927,"1,102.0",93,Sheffield Ave & Willow St,159,Claremont Ave & Hirsch St,Subscriber,Female,1993.0

**Changing Column names of data1 frame**

In [18]:
data1.rename(columns={data1.columns[0]:'trip_id', data1.columns[1]:'start_time', data1.columns[2]:'end_time', data1.columns[3]:'bikeid', data1.columns[4]: 'tripduration', data1.columns[5]: 'from_station_id', data1.columns[6]: 'from_station_name', data1.columns[7]: 'to_station_id', data1.columns[8]: 'to_station_name', data1.columns[9]: 'usertype',data1.columns[10]: 'gender',data1.columns[11]: 'birthyear'},inplace=True)

data1.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

**Making start_time and end_time columns consistent in data2 Dataframe**

In [19]:
# Convert "start_time" and "end_time" columns to datetime
data2['start_time'] = pd.to_datetime(data2['start_time'])
data2['end_time'] = pd.to_datetime(data2['end_time'])

# Format "start_time" and "end_time" columns with HH:MM:SS
data2['start_time'] = data2['start_time'].dt.strftime('%Y-%m-%d %H:%M:%S')
data2['end_time'] = data2['end_time'].dt.strftime('%Y-%m-%d %H:%M:%S')

# Display the resulting DataFrame with "start_time" and "end_time" in HH:MM:SS format
print(data2[['start_time', 'end_time']])

                  start_time             end_time
0        2018-01-04 00:04:00  2018-01-04 00:13:00
1        2018-01-04 00:06:00  2018-01-04 00:27:00
2        2018-01-04 00:07:00  2018-01-04 00:23:00
3        2018-01-04 00:07:00  2018-01-04 00:14:00
4        2018-01-04 00:10:00  2018-01-04 00:22:00
...                      ...                  ...
1048570  2018-06-30 11:38:00  2018-06-30 11:50:00
1048571  2018-06-30 11:38:00  2018-06-30 11:47:00
1048572  2018-06-30 11:38:00  2018-06-30 11:44:00
1048573  2018-06-30 11:38:00  2018-06-30 12:02:00
1048574  2018-06-30 11:38:00  2018-06-30 11:56:00

[1048575 rows x 2 columns]

In [20]:
data2.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,18000527,2018-01-04 00:04:00,2018-01-04 00:13:00,3819,499,22,May St & Taylor St,171,May St & Cullerton St,Subscriber,Male,1994.0
1,18000528,2018-01-04 00:06:00,2018-01-04 00:27:00,5000,"1,225.00",157,Lake Shore Dr & Wellington Ave,190,Southport Ave & Wrightwood Ave,Subscriber,Male,1965.0
2,18000529,2018-01-04 00:07:00,2018-01-04 00:23:00,5165,960,106,State St & Pearson St,106,State St & Pearson St,Customer,NaN,NaN
3,18000530,2018-01-04 00:07:00,2018-01-04 00:14:00,3851,434,241,Morgan St & Polk St,171,May St & Cullerton St,Subscriber,Male,1998.0
4,18000531,2018-01-04 00:10:00,2018-01-04 00:22:00,5065,709,228,Damen Ave & Melrose Ave,219,Damen Ave & Cortland St,Subscriber,Male,1983.0

In [21]:
data1.info()  #Gender and Birthyear have null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387145 entries, 0 to 387144
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            387145 non-null  int64
 1   start_time         387145 non-null  object
 2   end_time           387145 non-null  object
 3   bikeid             387145 non-null  int64
 4   tripduration       387145 non-null  object
 5   from_station_id    387145 non-null  int64
 6   from_station_name  387145 non-null  object
 7   to_station_id      387145 non-null  int64
 8   to_station_name    387145 non-null  object
 9   usertype           387145 non-null  object
 10  gender             364652 non-null  object
 11  birthyear          364823 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 35.4+ MB

In [22]:
data2.info() #Gender and Birthyear has null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1048575 non-null  int64
 1   start_time         1048575 non-null  object
 2   end_time           1048575 non-null  object
 3   bikeid             1048575 non-null  int64
 4   tripduration       1048575 non-null  object
 5   from_station_id    1048575 non-null  int64
 6   from_station_name  1048575 non-null  object
 7   to_station_id      1048575 non-null  int64
 8   to_station_name    1048575 non-null  object
 9   usertype           1048575 non-null  object
 10  gender             856342 non-null   object
 11  birthyear          857820 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 96.0+ MB

In [23]:
data3.info() #Gender and Birthyear has null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513570 entries, 0 to 1513569
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1513570 non-null  int64
 1   start_time         1513570 non-null  object
 2   end_time           1513570 non-null  object
 3   bikeid             1513570 non-null  int64
 4   tripduration       1513570 non-null  object
 5   from_station_id    1513570 non-null  int64
 6   from_station_name  1513570 non-null  object
 7   to_station_id      1513570 non-null  int64
 8   to_station_name    1513570 non-null  object
 9   usertype           1513570 non-null  object
 10  gender             1218574 non-null  object
 11  birthyear          1221990 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 138.6+ MB

In [24]:
data4.info() #Gender and Birthyear has null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642686 entries, 0 to 642685
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            642686 non-null  int64
 1   start_time         642686 non-null  object
 2   end_time           642686 non-null  object
 3   bikeid             642686 non-null  int64
 4   tripduration       642686 non-null  object
 5   from_station_id    642686 non-null  int64
 6   from_station_name  642686 non-null  object
 7   to_station_id      642686 non-null  int64
 8   to_station_name    642686 non-null  object
 9   usertype           642686 non-null  object
 10  gender             594304 non-null  object
 11  birthyear          596520 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 58.8+ MB

**CONCATENATE ALL 4 FILES**

In [25]:
data = pd.concat([data1, data2, data3, data4], axis=0, ignore_index=True)

In [26]:
data.shape

(3591976, 12)

In [27]:
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0

**Dropping Columns Gender and Birthyear**

In [28]:
data.drop(['gender','birthyear'],axis=1,inplace=True)
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber

**Adding A New Column 'ride_length' and then converting it to int64**

In [29]:
# Convert "start_time" and "end_time" columns to datetime
data['start_time'] = pd.to_datetime(data['start_time'])
data['end_time'] = pd.to_datetime(data['end_time'])

data['ride_length'] = data['end_time'] - data['start_time']

# Convert ride_length to integer representing seconds
data['ride_length_seconds'] = data['ride_length'].dt.total_seconds().astype('int64')

In [30]:
data.head(10)

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,ride_length,ride_length_seconds
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,0 days 00:05:23,323
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,0 days 00:06:17,377
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,0 days 00:48:24,2904
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,0 days 00:12:27,747
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,0 days 00:03:03,183
5,17536707,2018-01-01 00:56:15,2018-01-01 01:00:41,6298,266.0,304,Broadway & Waveland Ave,299,Halsted St & Roscoe St,Subscriber,0 days 00:04:26,266
6,17536708,2018-01-01 00:57:26,2018-01-01 01:02:40,1169,314.0,164,Franklin St & Lake St,174,Canal St & Madison St,Subscriber,0 days 00:05:14,314
7,17536709,2018-01-01 01:00:29,2018-01-01 01:13:43,6351,794.0,182,Wells St & Elm St,142,McClurg Ct & Erie St,Subscriber,0 days 00:13:14,794
8,17536710,2018-01-01 01:07:12,2018-01-01 01:31:53,1920,"1,481.0",99,Lake Shore Dr & Ohio St,99,Lake Shore Dr & Ohio St,Customer,0 days 00:24:41,1481
9,17536711,2018-01-01 01:07:54,2018-01-06 10:04:02,4783,"464,168.0",99,Lake Shore Dr & Ohio St,99,Lake Shore Dr & Ohio St,Customer,5 days 08:56:08,464168

**Add A column for 'day_of_week'**

In [31]:
data['start_time'] = pd.to_datetime(data['start_time'])

# Calculate the day of the week where 0 = Monday and 6 = Sunday
data['day_of_week'] = data['start_time'].dt.dayofweek

# Adjust the day numbering to match the requested format (1 = Sunday, 7 = Saturday)
data['day_of_week'] = (data['day_of_week'] + 1) % 7 + 1

# Display the resulting DataFrame with the "day_of_week" column
print(data[['start_time', 'day_of_week']])

                 start_time  day_of_week
0       2018-01-01 00:12:00            2
1       2018-01-01 00:41:35            2
2       2018-01-01 00:44:46            2
3       2018-01-01 00:53:10            2
4       2018-01-01 00:53:37            2
...                     ...          ...
3591971 2018-12-31 23:45:17            2
3591972 2018-12-31 23:48:48            2
3591973 2018-12-31 23:50:09            2
3591974 2018-12-31 23:55:04            2
3591975 2018-12-31 23:59:18            2

[3591976 rows x 2 columns]

In [32]:
#Checking the result
data.iloc[40900]

trip_id                               17588973
start_time                 2018-01-17 05:41:03
end_time                   2018-01-17 05:47:53
bikeid                                    4978
tripduration                             410.0
from_station_id                             23
from_station_name      Orleans St & Elm St (*)
to_station_id                              224
to_station_name         Halsted St & Willow St
usertype                            Subscriber
ride_length                    0 days 00:06:50
ride_length_seconds                        410
day_of_week                                  4
Name: 40900, dtype: object

In [33]:
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,ride_length,ride_length_seconds,day_of_week
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,0 days 00:05:23,323,2
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,0 days 00:06:17,377,2
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,0 days 00:48:24,2904,2
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,0 days 00:12:27,747,2
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,0 days 00:03:03,183,2

**Convert start_time and end_time columns to datetime64 datatype and ride_length datatype to timedelta64**

In [34]:
# Convert "start_time" and "end_time" columns to datetime
data['start_time'] = pd.to_datetime(data['start_time'])
data['end_time'] = pd.to_datetime(data['end_time'])

# Convert "ride_length" column to timedelta
data['ride_length'] = pd.to_timedelta(data['ride_length'])

In [42]:
data.drop(['ride_length'],axis=1,inplace=True)

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3591976 entries, 0 to 3591975
Data columns (total 15 columns):
 #   Column               Dtype
---  ------               -----
 0   trip_id              int64
 1   start_time           datetime64[ns]
 2   end_time             datetime64[ns]
 3   bikeid               int64
 4   tripduration         object
 5   from_station_id      int64
 6   from_station_name    object
 7   to_station_id        int64
 8   to_station_name      object
 9   usertype             object
 10  ride_length_seconds  int64
 11  day_of_week          int64
 12  start_week           int64
 13  start_month          int64
 14  start_quarter        int64
dtypes: datetime64[ns](2), int64(9), object(4)
memory usage: 411.1+ MB

In [36]:
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,ride_length,ride_length_seconds,day_of_week
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,0 days 00:05:23,323,2
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,0 days 00:06:17,377,2
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,0 days 00:48:24,2904,2
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,0 days 00:12:27,747,2
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,0 days 00:03:03,183,2

**Adding columns for Quarter, Month and Week by Parsing the start_time column**

In [37]:
data['start_week'] = data['start_time'].dt.week
data['start_month'] = data['start_time'].dt.month
data['start_quarter'] = data['start_time'].dt.quarter

<ipython-input-37-0ee26a18aeca>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  data['start_week'] = data['start_time'].dt.week

In [38]:
data.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,ride_length,ride_length_seconds,day_of_week,start_week,start_month,start_quarter
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,323.0,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,0 days 00:05:23,323,2,1,1,1
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,377.0,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,0 days 00:06:17,377,2,1,1,1
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,"2,904.0",98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,0 days 00:48:24,2904,2,1,1,1
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,747.0,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,0 days 00:12:27,747,2,1,1,1
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,183.0,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,0 days 00:03:03,183,2,1,1,1

In [45]:
data.dtypes

trip_id                         int64
start_time             datetime64[ns]
end_time               datetime64[ns]
bikeid                          int64
tripduration                   object
from_station_id                 int64
from_station_name              object
to_station_id                   int64
to_station_name                object
usertype                       object
ride_length_seconds             int64
day_of_week                     int64
start_week                      int64
start_month                     int64
start_quarter                   int64
dtype: object

**Exporting the cleaned data to a csv file**

In [44]:
data.to_csv('FinalData.csv', index=False)

**DATA IS READY FOR ANALYSIS!!!**

In [46]:
df = pd.read_csv("drive//MyDrive//Google Data Analytics Capstone//FinalData.csv")

In [47]:
df.shape

(3591976, 15)

In [ ]:
df.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'ride_length', 'day_of_week',
       'start_week', 'start_month', 'start_quarter'],
      dtype='object')